# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=50)),
                ('time', models.TextField(max_length=50)),
                ('fk_content', models.TextField(max_length=50)),
            ],
        ),
    ]
